version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-lab2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost/api
    container_name: frontend_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    # environment:
    #   - REACT_APP_API_URL=http://localhost/api
    depends_on:
      - db
      - api

  api:
    build: ./api
    container_name: api_server
    # volumes:
    #   - ./api:/api
    environment:
      SERVER_NAME: WEBSITE-1
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "3000:3000"
    depends_on:
      - db

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./frontend/build:/usr/share/nginx/html
  #   depends_on:
  #     - api

volumes:
  db_data:
