version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres-lab1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  website:
    build: ./website
    container_name: website_server
    volumes:
      - ./website:/website
    environment:
      SERVER_NAME: WEBSITE-1
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  chat:
    build: ./chat
    container_name: chat_server
    volumes:
      - ./chat:/chat
    ports:
      - "8001:8001"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - website
      - chat

volumes:
  db_data:
